# rake asset:packager:build_all
--- 
javascripts: 
- base:
  - jquery
  - jquery-ui
  - jquery_ujs
  - rails
  - application
  - autocomplete-rails
stylesheets: 
- base: 
  - default
  - icons
- agent:
  - agent
  - icons
- page:
  - page
- admin:
  - default
  - admin
- dialog:
  - dialog
