# rake asset:packager:build_all
--- 
javascripts: 
- base:
  - jquery
  - jquery-ui
  - jquery_ujs
  - autocomplete-rails
  - jquery.cycle.all.2.74
  - jquery.jqzoom-core-pack 
  - application
stylesheets: 
- base: 
  - default
  - icons
- agent:
  - agent
  - icons
- page:
  - page
  - jquery.jqzoom
- admin:
  - default
  - admin
- dialog:
  - dialog
