# Configuration options can be accessed as
# configatron.site_name

development: &local
    site_name: Пилотска Станция - Варна
    site_namemobile: Пилотска станция - Варна
    site_url: pilotorder.bg
    
    company_name: Pilot Station Varna
    admin_email: office@pilotorder.bg
    
    support_name: bstconsult.com
    support_email: support@pilotorder.bg
    
    site_envnote: Local Server

production:
  <<: *local

staging:
  <<: *local

test:
  <<: *local
