# Configuration options can be accessed as
# configatron.site_name

development: &local
    site_name: ПоръчайПилот.БГ
    site_namemobile: ПоръчайПилот.БГ
    site_url: baseapp2.local
    
    company_name: Pilot Station Varna
    admin_email: dev@pilotorder.bg
    
    support_name: 
    support_email: support@pilotorder.bg
    
    site_envnote: Local Server

production:
    site_name: BaseApp2
    site_namemobile: BaseApp2
    site_url: www.baseapp2.com
    
    company_name: Development Company
    admin_email: admin@baseapp2.com
    
    support_name: Development Company
    support_email: support@baseapp2.com
    
    site_envnote: Production Server
  
staging:
  <<: *local

test:
  <<: *local
